### ISSUE TITLE
1.2.1 hide snippets

### ISSUE THREAD

**Issue by Javacym** [sadovnychyi/autocomplete-python#135]
new version 1.2.1 hide language-python package snippets
env is snippet #!/usr/bin/env python,but 1.2.1 hide it
when i disable autocomplete-python,env snippet work.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/11647366/1e485f90-9da2-11e5-926d-93007b8872cb.png)
I still can see them. Is it what are you talking about?

**Comment by Javacym** [comment]
enable:
![image](https://cloud.githubusercontent.com/assets/13167757/11647585/794e5064-9da4-11e5-957a-92a102439fcb.png)
disable:
![image](https://cloud.githubusercontent.com/assets/13167757/11647593/9bbf4658-9da4-11e5-8d69-ffb652c65db6.png)

**Comment by sadovnychyi** [comment]
Try to change priority values here:
https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L12-L14

**Comment by Javacym** [comment]
![image](https://cloud.githubusercontent.com/assets/13167757/11647713/7887cbc2-9da6-11e5-8bea-dd0ea92b8b48.png)
I change true to false,then i work. thanks a ton

**Comment by pierregodard** [comment]
@sadovnychyi I'm running into this issue only for certain snippets. With:
```
atom -v
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
``` 
```
apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2
```
and
```
├── autocomplete-plus@2.29.2
├── autocomplete-snippets@1.10.0
```
`├── autocomplete-python@1.8.2`

a snippet like `class` is hidden in the suggestion list if `autocomplete-python` is enabled but becomes listed again if `autocomplete-python` is disabled. In both cases, `tab` will trigger the snippet.

**Comment by sadovnychyi** [comment]
This is because autocomplete-python provides it's own completions for these keywords, ins't? Maybe just rename your snippets?

**Comment by pierregodard** [comment]
thank you for your answer. it is very likely that `autocomplete-python`  somehow overwrites those, yes. 

However, as these snippets are defined in the core `language-python` package, and since they are replaced by the mere keyword completion when they initially were able to trigger something richer (in the case of `class` for example, we get a full template with the snippet from `language-python` instead of just the keyword completion with `autocomplete-python`), I'm not sure this is the desired behavior. 

I don't know though if it's possible to make them co-exist.

**Comment by sadovnychyi** [comment]
The issue is that autocomplete-plus removes completions with same name. What you can do however is open your snippets.cson and copy all snippets you want to use from [here](https://github.com/atom/language-python/blob/master/snippets/language-python.cson) while changing their prefixes like `'prefix': 'class'` -> `'prefix': 'class_snippet'` or something.

You can also try to play with different priorities [here](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L16-L17).

**Comment by sadovnychyi** [comment]
Check new option in v1.8.3. The value of suggestionPriority=1 should work for you.

**Comment by pierregodard** [comment]
wonderful, it does work! thank you very much!
