### ISSUE TITLE
Fuzzy matches appear despite feature being turned off

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#146]
I've posted [here](https://github.com/sadovnychyi/autocomplete-python/issues/140#issuecomment-165965304) about fuzzy matches that appear if there are no other results, it turns out they appear even if there are regular results. The expected behavior would be to see no fuzzy matches at all if they are disabled.

![capture](https://cloud.githubusercontent.com/assets/7513068/11912616/7c618426-a64e-11e5-9a61-d3c3585db3d7.PNG)

![capture](https://cloud.githubusercontent.com/assets/7513068/11912614/4c47cffc-a64e-11e5-85ad-0852e9aa168b.PNG)

**Comment by sadovnychyi** [comment]
We could use more string filtering for [cached responses](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L270-L273), but I'm not sure that it's required. I was even thinking to remove the setting to disable fuzzy completions.

Why you don't want to receive fuzzy completions?

**Comment by dessant** [comment]
@sadovnychyi, because it is still slow. Since it was enabled by default, completions appear after seconds, this is why i've discovered that it is happening despite being turned off. Users should be given the choice to disable it, even more so when it degrades performance.

**Comment by sadovnychyi** [comment]
Have you tried it with latest version? I put a lot of effort to make fuzzy completions fast. They could be even a little bit faster in same cases, since we call Jedi only for first character, and then complete everything from cache.

**Comment by dessant** [comment]
Yes, i'm using the latest release of both atom and autocomplete-python.

**Comment by dessant** [comment]
I can imagine that it means a lot of work to maintain this plugin, and the value you provide is huge considering that it serves the whole atom community with the only viable autocomplete package for python, so thank you for that.

As you see, with tens of thousands of devs using the plugin, having older and newer devices, there will be people experiencing slowness even if you continue otimizing fuzzy completion, so it is sensible to keep a toggle for it in the settings panel and offer a compromise for those who have problems.

**Comment by sadovnychyi** [comment]
Can you please provide a code snippet where I can get fuzzy completions when they are off?
Just tried to type some things, cannot get anything.

Maybe, you get a response from Jedi for `def on_` and for the moment when you type `def on_d` you didn't get any response from Jedi *yet* thus autocomplete-plus just filtered existing results for you using built-in fuzzy matcher. I'm not sure that this even possible, but cannot get other explanation.

With fuzzy matcher turned on, you should see same request IDs for every character in the word after a first one. But when it's off – you should see different request IDs for each character.

On slow machines and/or huge projects, calling Jedi to complete `o` is much more time consuming operation than completing for `on_db`, but I believe it's still faster to get all completions for `o` and then re-use them with each possible suffix instead of making a call for each.

But it's making sense to not use fuzzy completions if you cannot get completions for single character in reasonable amount of time.

For optimization purposes, what do you think about a setting to disable completion before you type N characters? We could respect a setting from autocomplete-plus:
![image](https://cloud.githubusercontent.com/assets/193864/11917183/0c01943e-a737-11e5-8ca4-286b20b7b253.png)

**Comment by dessant** [comment]
Add this code to an empty python file:

```python
class FadeTransition():
    pass

def form_cont():
    pass

```

Continue it by typing `fro` on a new line and you should see this:

![capture](https://cloud.githubusercontent.com/assets/7513068/11917465/c3f6617c-a710-11e5-9ef6-bf45409761fc.PNG)

**Comment by dessant** [comment]
@sadovnychyi, the minimum word length would be a nice setting, the default value of autocomplete-plus could be inherited, with an option to set a different value in autocomplete-python settings.

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/11917504/8ddf7acc-a744-11e5-8739-de606ef81484.png)

Can you confirm that you are getting response from jedi after typing `o`?

**Comment by dessant** [comment]
I think you're right about the default provider results creeping in, there are two settings affecting this in autocomplete-plus:

![capture](https://cloud.githubusercontent.com/assets/7513068/11917491/fd0ad79e-a711-11e5-94ef-1c71d8a0e521.PNG)

If strict matching is activated there, the fuzzy matches do not appear with the previous example. It seems the different providers offer results on top of the default provider, we will still get results from the default one, unless we disable it with the last setting.

**Comment by dessant** [comment]
![capture](https://cloud.githubusercontent.com/assets/7513068/11917519/22fd355e-a713-11e5-98b4-e3872bf4268b.PNG)

**Comment by dessant** [comment]
If this is expected, I guess mentioning the strict matching option below the fuzzy completion setting or in the readme would be enough.
