### ISSUE TITLE
Exceptions originating from completion.py are silently eaten

### ISSUE THREAD

**Issue by dessant** [sadovnychyi/autocomplete-python#147]
I have added `raise Exception()` in [_deserialize](https://github.com/sadovnychyi/autocomplete-python/blob/c7cf07c2bbbdcd19380a6fe9ddd6afd60b1d9044/lib/completion.py#L200), but no popup is shown with the exception. I've also activated outputting provider errors (but exceptions originating from completion.py should be visible even with this seeting turned off) and the error is still not shown nor logged in debug logs.

With the above change the queue is just filled up and the process keeps being restarted. The correct behavior would be to show an error popup so users can use the ui provided by atom to submit and auto fill bug reports, otherwise issues are obscured and become harder to identify.

**Comment by sadovnychyi** [comment]
Most of python level exceptions are originated from Jedi, and I don't really want them to be reported here.  That's why they are hidden under a setting by default.

They all catched in a single place and written into stderr [here](https://github.com/sadovnychyi/autocomplete-python/blob/c7cf07c2bbbdcd19380a6fe9ddd6afd60b1d9044/lib/completion.py#L264-L267).

Then, [here](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/provider.coffee#L48-L56), we catch it on Atom level, and, if setting is enabled – we output an error message. They should be **always** written into debug logs as you can see there.

Well, it supposed to be this way. I just tested it and can confirm that it is broken. I'm not sure if its something from my side or from Atom's BufferedProcess. But the stderr callback isn't called for some reason.

**Comment by dessant** [comment]
I agree that exceptions originating from jedi should be hidden under provider errors, but yeah, this one is not a provider error so it should be surfaced regardless of that setting.

**Comment by dessant** [comment]
It could not update:
```
Updating package autocomplete-python to vnull failed Error: Updating to “autocomplete-python@1.2.4” failed.
    at C:\Users\prc\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:396:21
    at exit (C:\Users\prc\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\prc\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\prc\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) undefined
```

**Comment by sadovnychyi** [comment]
Well this looks really strange especially since I've modified only python code, didn't touch coffeescript at all. Can you uninstall and install it again?

**Comment by dessant** [comment]
Sure, doing it now.

**Comment by dessant** [comment]
Ok, it activated nicely after a clean reinstall. The popup is shown now, but only if provider errors are set to be shown.

**Comment by dessant** [comment]
@sadovnychyi, could you reopen the issue?

**Comment by sadovnychyi** [comment]
Sure, but please explain desired behaviour of `output provider error` settings. Right now it hides every python related error. You want to limit it to Jedi errors only?

**Comment by dessant** [comment]
Yes, that is right, you could put the jedi api calls in a try except, and log those errors if the setting is activated. The rest of the unhandled exceptions in the plugin should be shown even when that setting is turned off. This way the fatal errors in the plugin will not be hidden by default.
