### ISSUE TITLE
Goto Definition does not always work

### ISSUE THREAD

**Issue by exploide** [sadovnychyi/autocomplete-python#162]
It seems there are some cases where goto definition (and renaming) does not work:

```python
# test goto definition for my_list
my_list = [1, 2, 3, 4, 5]
length = len(my_list) # does not work (neither renaming)
print(my_list) # works

# test goto definition for idx
idx = 3
v = my_list[idx] # does not work
print(idx) # works
```

But beside that: Awesome feature :+1: 

Affected version: autocomplete-python 1.4.3

**Comment by sadovnychyi** [comment]
Strange. Nothing works for me at all in this example.

**Comment by julee** [comment]
statement such as:
'xxxxx'.encode('utf-8')
cannot goto the method encode's definition, thought autocomplete works  here.
Is this a bug?

**Comment by sadovnychyi** [comment]
Maybe it's not pure python method and it's written in C?

**Comment by JamesStidard** [comment]
These work for me. Version: 1.8.6

**Comment by exploide** [comment]
Can confirm this. My examples work now :)

I will close this issue.

Since julee's example is a bit different since it targets the standard library (and may be a C function?!) this should be a different issue.

**Comment by deepio** [comment]
### Prerequisites

* [X] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] ~~It's always helpful if you include debug logs with your issue:~~
  * ~~Go to package settings to enable them~~
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * ~~Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.~~

No error/debug logs to speak of

### Steps to Reproduce

***

#### This seems to work
```bash
pip install mido
pip install jedi
```
```python
import jedi
import mido

source = open('./env/lib/python3.7/site-packages/mido/backends/backend.py', 'r').read()
script = jedi.Script(source, 72, )
print(script.goto_definitions())
```
- `$ [<Definition instance str>]`

<kbd>alt</kbd> + <kbd>command</kbd> + <kbd>G</kbd> on `goto_definitions()` correctly goes to the definition.

#### This does not seem to work
```python
mido.open_input()
```
- <kbd>alt</kbd> + <kbd>command</kbd> + <kbd>G</kbd> on open_input() gives:
`>>> Definition not found` 


**Expected behavior:** 
Find this: 
```python
    def open_input(self, name=None, virtual=False, callback=None, **kwargs):
        """Open an input port.

        If the environment variable MIDO_DEFAULT_INPUT is set,
        if will override the default port.

        virtual=False
          Passing True opens a new port that other applications can
          connect to. Raises IOError if not supported by the backend.

        callback=None
          A callback function to be called when a new message arrives.
          The function should take one argument (the message).
          Raises IOError if not supported by the backend.
        """
```

**Actual behavior:** 
Definition was not found.
