### ISSUE TITLE
Function arguments suggestion after opening bracket

### ISSUE THREAD

**Issue by kitlbast** [sadovnychyi/autocomplete-python#172]
Hi,

currently I can see a list of arguments suggests only if I start typing argument name or after opening bracket with coma and whitespace:

<img width="221" alt="screenshot 2016-02-02 18 35 56" src="https://cloud.githubusercontent.com/assets/59706/12758349/17c47abc-c9dc-11e5-9bb2-2769c01ba8c5.png">

It would be nice to have such dropdown to appear right after opening bracket. I didn't use arguments completion and such a thing will produce nice suggestions. Currently I have to move cursor back before opening bracket and then trigger autocomplete to see function signature. I did try to change "Regex To Trigger Autocompletions" to do it after function's "(" but from logs seems like Jedi doesn't return any result.

**Comment by sadovnychyi** [comment]
This is because of bracket matcher which adds closing bracket just after you open it. But it works now when I manually activate autocomplete-plus command.

**Comment by kitlbast** [comment]
Thanks a lot, very nice plugin.

**Comment by pchomik** [comment]
I tried this with latest plugin version and I cannot get this popup menu. Could you help?

**Comment by sadovnychyi** [comment]
The prerequirement for this is to set `Autocomplete function parameters` to none.

Then, instead of automatically inserting list of arguments, autocomplete will be triggered:

![sample](https://cloud.githubusercontent.com/assets/193864/13389704/f2e7d016-df04-11e5-9fe1-e7a5a1d63fcb.gif)

If you have `Autocomplete function parameters` setting to set on something else, you should get arguments completed here automatically.

If it does not work for you in all cases, check the README about non-standard keyboard layouts section.
https://github.com/sadovnychyi/autocomplete-python/blob/master/README.md#common-problems
To debug it, try to turn on package debug logs in the settings, and look for `Trying to complete arguments on keyup event` message. If it's not there – it's definitely keyboard layout problem.
![image](https://cloud.githubusercontent.com/assets/193864/13389764/4fc55d3a-df05-11e5-91f8-8f175f277516.png)

**Comment by kitlbast** [comment]
Is it possible to add an option to not show autocomplete by default after bracket, but by keyboard triggering?

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/13390627/917471ee-df0a-11e5-9ac6-44c122bfe0e5.png)

Just remove `(` character from here. So something like:
```regex
([\.\ ]|[a-zA-Z_][a-zA-Z0-9_]*)
```

**Comment by kitlbast** [comment]
I have turned off option Show suggestions on Keystroke in autocomplete-plus, so I don't expecting to see autocomplete until I trigger it by ctrl+space. Removing "(" from regex totally disables autocomplete after bracket, keyboard triggering stops working. Probably, "Show suggestions on Keystroke" should be considered in after-bracket autocomplete behavior?

**Comment by sadovnychyi** [comment]
Yeah, we can read that core setting and respect it. Could you fill an issue for this please? I will fix it once I got a minute.

**Comment by kitlbast** [comment]
Sure! #182
