### ISSUE TITLE
autocomplete-python's configuration is used&relied by Nuclide's python autocomplete function

### ISSUE THREAD

**Issue by wonderbeyond** [sadovnychyi/autocomplete-python#236]
I have been an autocomplete-python user for a long time.
Today I installed the [Nuclide](https://nuclide.io/) package, found it also has [Autocomplete&Jump support for python](https://nuclide.io/docs/languages/python/).

My python projects were bound to virtualenvs, I haven't told Nuclide where my python executable path is, However Nuclide just works "correctly"! It could navigate me to symbols definition from virtualenvs.
Then I guessed Nuclide must be using autocomplete-python's configuration, as below:

![image](https://cloud.githubusercontent.com/assets/228361/18985679/a631bd84-872b-11e6-92bc-25229656351a.png)

After I disabled autocomplete-python package, then Nuclide's autocomplete function also didn't work , my guess is right!

So, How could these happen? Does the two packages share some common component? @sadovnychyi @Facebook

**Comment by sadovnychyi** [comment]
autocomplete-python is a "provider" for nuclide package, just like it's a provider of completions for autocomplete-plus. The implementation is [here](https://github.com/sadovnychyi/autocomplete-python/blob/master/lib/hyperclick-provider.coffee). It's actually mentioned in the readme :)

**Comment by wonderbeyond** [comment]
So, It's you have did special support for Hyperclick(embed by Nuclide)?
However Nuclide only say

> Nuclide integrates Jedi to provide fast, detailed, and context-aware autocompletion.
> ...
> Nuclide allows you to directly jump to definition for local or imported symbols alike.

It didn't mention it's leveraging hyperclick's interface.

**Comment by sadovnychyi** [comment]
What I did is implemented support for [hyperclick](https://atom.io/packages/hyperclick) package (see "providers"), which is now part of nuclide. I didn't know that nuclide has python support, and they basically re-implemented this package. Cannot give any comments about this, but now I'm curious as well.

**Comment by wonderbeyond** [comment]
According to Nuclide‘s documentation, It shoud **fully work without autocomplete-python**.
I am guessing Nuclide cannot do autocomplete&jump by its primary method, because I just didn't tell my python path to it. So Nuclide chose to leverage hyperclick interface(you just did the support).

**Comment by sadovnychyi** [comment]
Yep.. So no issues here, right?

**Comment by wonderbeyond** [comment]
I think so. I post issue here just because I thing you can figure out the reason.
Many thanks!

**Comment by wonderbeyond** [comment]
> I didn't know that nuclide has python support, and they basically re-implemented this package. 

But I don't think such a big package can do everything well.
For example, I just don't know how to tell where my python path is, because I am using virtualenvs, having different python paths for different projects. The settings tip didn't prompt me the probability:

![image](https://cloud.githubusercontent.com/assets/228361/18988246/53cd7170-8738-11e6-9fdb-a7aa2f818ab8.png)

If you are interested, can you review Nuclide's work and try convince them to integrate autocomplete-python, but not re-implemente everything.

**Comment by sadovnychyi** [comment]
I don't think that they would agree on that, since they use javascript with flow instead of coffeescript, it would require huge rewriting of this package, basically what they did. While they don't have support for multiple python versions/executables – it's a matter of their desire to implement it, especially since they are paid facebook engineer's and I'm doing this in my free time.

Ping contributors of python package in nuclide @peterhal @hansonw @zertosh @tyangliu @reesjones. Should both of this packages exist independently?

**Comment by tyangliu** [comment]
Nuclide needed its own providers for autocompletion (amongst other things like lint/outline providers) primarily because it needed to support remote development (and Buck dependencies). In this case the code base and Jedi live on a devserver, which talks to the Atom provider via Nuclide's RPC system. This use case is less common outside of Facebook, so I think it makes sense for autocomplete-python to stay separate as a lighter package. Though feel free to file an issue on Nuclide if you have a feature request for it.

**Comment by sadovnychyi** [comment]
Thanks for a comment. It's completely makes sense for me.
