### ISSUE TITLE
Are the venvs in $PROJECT working?

### ISSUE THREAD

**Issue by ergo** [sadovnychyi/autocomplete-python#25]
Hi,

I've tried multiple combinations of setting up the plugin to recognize my virtualenvs.
like: $PROJECT/venv/lib/python3.4/site-packages;$PROJECT/venv/lib/python2.7/site-packages

and then point "Path to python" to an empty venv with just python 3.4 counting that extra path will pick up project's virtualenv.
The only way I got this functionality actually working was when i set the path to python to:
/home/ergo/workspace/projectname/venv/bin

Would it be possible to also allow path to python to be something like:
$PROJECT/venv/bin?

This would be even better because it would auto work for both py2.x and 3.x projects eventually.

**Comment by sadovnychyi** [comment]
Am I right that ability to use $PROJECT inside of "Path to python" will solve your problems?

**Comment by sadovnychyi** [comment]
I'm not sure, but I think that autocompletion should work for both python2 and python3 packages regardless of the python's version in python path. Can you confirm that `$PROJECT/venv/lib/python2.7/site-packages` works only when you have python27 in your "path to python" and vice versa?

**Comment by ergo** [comment]
I did:
$PROJECT/venv27/lib/python2.7/site-packages
and it indeed seems to work, it is just 3.x version that doesn't seem to work for me.

**Comment by ergo** [comment]
Eh.. sorry scratch that - its not working - I didnt remove previous path to python.

**Comment by ewrogers** [comment]
I have a similar issue/request and I thought I'd chime in here instead of creating a separate issue.

It seems to be common convention to create a **venv** folder in the project root.

I have had success by changing the Python directory to `C:\Projects\project_name\venv\Scripts\` but that makes it clunky when task-switching between projects that do not use one.

My suggestion would be to add another package settings for **Virtual Env Path** and it would default to `$PROJECT\venv`. The autocomplete engine could first check to see if a virtual env exists, and fallback to the global Python installation if needed.

**Comment by jfmatth** [comment]
I have fixed this as well by making sure I point the extra path to the site-packages folder, just like above.

**Comment by sadovnychyi** [comment]
I think that `$PROJECT/venv/lib/site-packages` should work for both python2 and python3, but it seems like it didn't for @ergo. Anybody tried it with different python versions? Since it a bit more complicated to use `$PROJECT/venv/bin` for python executable path, I would like to avoid it.

**Comment by sadovnychyi** [comment]
Closing this in favor of #66.
