### ISSUE TITLE
Autocomplete with sshfs-mounted directories

### ISSUE THREAD

**Issue by brainstorm** [sadovnychyi/autocomplete-python#64]
Would it be possible to support autocompletion when directories are on remote machines?

**Comment by sadovnychyi** [comment]
If python is able to import such paths – it should work. Have you tried it? You probably should add mounted directory into extra paths.

**Comment by brainstorm** [comment]
Yes, I have tried autocompleting, but only global functions and keywords are autocompleted (i.e `len()`)... methods from an object from the current project do not get listed/expanded at all :/

**Comment by sadovnychyi** [comment]
Does it works for you on non sshfs-mounted directories? Don't forget to try extraPaths package setting.

**Comment by brainstorm** [comment]
Yes, it does work with non sshfs directories (locally) :-S

Should the extraPaths point to the $PROJECT only or should it additionally point to the virtualenv (even when $PROJECT was installed via `python setup.py develop`?)

**Comment by sadovnychyi** [comment]
First try absolute path without using $PROJECT variable.
Like `/path/ssh-mounted/site-packages/` or something.

**Comment by brainstorm** [comment]
No luck, it does not autocomplete still... can you reproduce this issue on your system via a remote SSHFS mount?

**Comment by sadovnychyi** [comment]
Sorry, wasn't able to mount remote directory on OSX.

**Comment by brainstorm** [comment]
Oh, sorry, I should have told how, it's pretty straightforward actually:

$ brew install osxfuse

And then install this for a more fancy UI to define and mount volumes:

http://macfusionapp.org/

Quite handy ;)

**Comment by sadovnychyi** [comment]
So, yeah – it's works for me. Its works when I'm trying to import remote package as well as when I'm inside of remote folder. It's really slow for me though, the whole Atom is slowed down because of remote folder.

![image](https://cloud.githubusercontent.com/assets/193864/10600444/6a5281ee-773d-11e5-9659-acfbf23c00d0.png)

I can see "bla" var from imported "bla.py" inside of "bla2.py". Everything is inside of remote folder.

Check maybe you are missing __init__.py or something?
